version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      remotion:
        patterns:
          - 'remotion'
          - '@remotion/*'
      eslint:
        patterns:
          - 'eslint'
          - '@eslint/*'
          - 'typescript-eslint'
          - 'eslint-*'
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
